### ISSUE TITLE
pos_data is dataset.py

### ISSUE THREAD

**Issue by hichem-abdellali** [dongkwonjin/Semantic-Line-SLNet#1]
Hi,

what are the 10 component of the `pos_data` in dataset.py line 82, could you please provide information about it?
I guess that the last 4 elements are the ground-truth regression offset

Thanks

**Comment by dongkwonjin** [comment]
Hi,

10 components are composed of the coordinates of the two end-points (4), binary vector for classification (2), and line offset for regression (4).

Thanks

**Comment by djidan10** [comment]
Hi

Thanks for your reply, Could you please share how to calculate the line offset for regression? 

Thanks

**Comment by djidan10** [comment]
.

**Comment by dongkwonjin** [comment]
Hi! We uploaded source codes for preprocessing data!
