### ISSUE TITLE
candidate lines generation

### ISSUE THREAD

**Issue by cannonli7** [dongkwonjin/Semantic-Line-SLNet#2]
Thanks for your work. Could you please upload the code for generating candidate lines? The details is still not very clear for me

**Comment by tj-byun** [comment]
+1 Same here.

**Comment by duyuanfu** [comment]
Thanks for your work，can you please provide these file 'root/SEL/data/detector/detector_train_candidates.pickle' and 'root/SEL/data/detector/detector_test_candidates.pickle'

**Comment by dongkwonjin** [comment]
Hi! Thank you for your interest. We are sorry for the late reply. We uploaded source codes for preprocessing data!

**Comment by cannonli7** [comment]
> Hi! Thank you for your interest. We are sorry for the late reply. We uploaded source codes for preprocessing data!

Thanks
