### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by duyuanfu** [dongkwonjin/Semantic-Line-SLNet#3]

**Comment by duyuanfu** [comment]
How do you make 'detector_test_candidates.pickle' files ?

**Comment by duyuanfu** [comment]
and how to make tran.pickle and test.pickle?

**Comment by dongkwonjin** [comment]
Hi! Thank you for your interest. We are sorry for the late reply. 

You can make those files simply by converting the txt files in the original SEL dataset to pickle ones :)
