### ISSUE TITLE
How do I generate "./SEL/data/DNet/detector_train_candidates.pickle" file.

### ISSUE THREAD

**Issue by duyuanfu** [dongkwonjin/Semantic-Line-SLNet#4]
How do I generate "./SEL/data/DNet/detector_train_candidates.pickle" file.

**Comment by dongkwonjin** [comment]
Hi! Thank you for your interest. We are sorry for the late reply. We uploaded source codes for preprocessing data!

**Comment by duyuanfu** [comment]
Thanks!
